--1. 학생이름과 주소지를 표시하시오. 단, 출력 헤더는 "학생 이름", "주소지"로 하고,정렬은 이름으로 오름차순 표시하도록 핚다.
SELECT *
FROM   TB_STUDENT ;

SELECT STUDENT_NAME AS "학생 이름", 
       STUDENT_ADDRESS AS 주소지
FROM   TB_STUDENT ;

--2. 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력하시오.
SELECT *
FROM   TB_STUDENT ;

SELECT STUDENT_NAME,
       STUDENT_SSN
FROM   TB_STUDENT
WHERE  ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC ;

--3. 주소지가 강원도나 경기도인 학생들 중 1900 년대 학번을 가진 학생들의 이름과 학번,주소를 이름의 오름차순으로 화면에 출력하시오. 단, 출력헤더에는 "학생이름","학번","거주지 주소" 가 출력되도록 핚다.
SELECT *
FROM  TB_STUDENT ;

SELECT *
FROM  TB_CLASS ;

SELECT *
FROM  TB_DEPARTMENT ;

SELECT *
FROM  TB_GRADE ;

SELECT STUDENT_NAME,
       STUDENT_NO,
       STUDENT_ADDRESS
FROM   TB_STUDENT
WHERE ((STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%') AND (SUBSTR(STUDENT_NO,1,1)) = '9')
ORDER BY 1;

---4.현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인할수 있는 문장을작성하시오.(법학과의 '학과코드'는 학과 테이블(TB_DEPARTMENT)을 조회해서 찾자
SELECT *
FROM   TB_PROFESSOR ;

SELECT *
FROM   TB_DEPARTMENT ;

SELECT PROFESSOR_NAME,
       PROFESSOR_SSN
FROM   TB_PROFESSOR
WHERE  DEPARTMENT_NO = '005'
ORDER  BY 2 ;

--5.  2004 년 2 학기에 'C3118100' 과목을 수강핚 학생들의 학점을 조회하려고 핚다. 학점이 
--높은 학생부터 표시하고, 학점이 같으면 학번이 낮은 학생부터 표시하는 구문을 작성해보시오.

SELECT *
FROM   TB_GRADE ;
 
SELECT STUDENT_NO,
       POINT
FROM   TB_GRADE
WHERE  TERM_NO = '200402'
AND    CLASS_NO = 'C3118100'
ORDER BY 2 ;

--6. 학번, 이름, 학과이름을 학생이름으로 오름차순정렬하여 출력하시오

SELECT *
FROM   TB_STUDENT ;

SELECT *
FROM  TB_DEPARTMENT ;

SELECT STUDENT_NO,
       STUDENT_NAME,
       DEPARTMENT_NAME
FROM   TB_STUDENT
JOIN   TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2 ;


--7. 춘기술대학교의 과목 이름과 과목의 학과 이름을 출력하세요
SELECT *
FROM   TB_DEPARTMENT ;

SELECT *
FROM   TB_CLASS ;

SELECT CLASS_NAME,
       DEPARTMENT_NAME
FROM   TB_DEPARTMENT
JOIN   TB_CLASS USING(DEPARTMENT_NO) ;

--8. 과목별 교수이름을 찾으려고 한다. 과목이름과 교수이름을 출력하는 SQL문을 작성하시오
SELECT *
FROM  TB_CLASS ;

SELECT *
FROM  TB_PROFESSOR ;

SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM   TB_PROFESSOR
JOIN   TB_CLASS USING(DEPARTMENT_NO) ;

SELECT C.CLASS_NAME,
       P.PROFESSOR_NAME
FROM   TB_PROFESSOR P
JOIN   TB_CLASS C ON(P.DEPARTMENT_NO = C.DEPARTMENT_NO);
---외래키끼리라서 안되나???
SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM   TB_PROFESSOR
JOIN   TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN   TB_CLASS USING(DEPARTMENT_NO) ;

SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM   TB_PROFESSOR , TB_CLASS 
JOIN   TB_DEPARTMENT USING(DEPARTMENT_NO);

----이거는 3개연결했는데 왜 안되지?
SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM   TB_PROFESSOR
JOIN   TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN   TB_CLASS USING(CLASS_NO) ;

--9. 8번의 결과 중 '인문사회'계열에 속한 과목의 교수이름을 찾으려고 할때, 이에 해당하는 과목 이름과 교수이름을 출력하시오
SELECT *
FROM   TB_DEPARTMENT ;

SELECT *
FROM   TB_GRADE ;

SELECT *
FROM   TB_STUDENT ;

SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM   TB_PROFESSOR R
JOIN   TB_CLASS_PROFESSOR CR USING(PROFESSOR_NO)
JOIN   TB_CLASS C USING(CLASS_NO)
JOIN   TB_DEPARTMENT D ON(D.DEPARTMENT_NO = R.DEPARTMENT_NO)
WHERE  CATEGORY = '인문사회';

--10. '음악학과' 학생들의 평점을 구하려고 한다.음악학과 학생들의 "학번", "학생 이름", "전체 평점"을 출력하는 SQL문장을 작성하시오(평점은 소수점 1자리까지만 반올림하여 표시한다)
SELECT S.STUDENT_NO,
       S.STUDENT_NAME,
       ROUND(AVG(POINT),1)
FROM   TB_STUDENT S
JOIN   TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN   TB_GRADE G ON(G.STUDENT_NO = S.STUDENT_NO)
WHERE  DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME ;

--11. 학번이 A313047인 학생이 학교에 안나오고있다.지도교수에게 내용을 전달하기위해 학과이름, 학생이름,지도교수이름이 필요하다.
--(헤더는 학과이름, 학생이름,지도교수이름으로출력)
SELECT *
FROM   TB_STUDENT ;
SELECT *
FROM   TB_DEPARTMENT ;
SELECT *
FROM   TB_PROFESSOR ;
SELECT *
FROM   TB_CLASS_PROFESSOR ;
SELECT *
FROm   TB_GRADE ;

SELECT DEPARTMENT_NAME AS 학과이름,
       STUDENT_NAME AS 학생이름,
       PROFESSOR_NAME AS 지도교수이름
FROM   TB_STUDENT   
JOIN   TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN   TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE  STUDENT_NO = 'A313047' ;

SELECT DEPARTMENT_NAME AS 학과이름,
       STUDENT_NAME AS 학생이름,
       PROFESSOR_NAME AS 지도교수이름
FROM   TB_STUDENT S   
JOIN   TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN   TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE  STUDENT_NO = 'A313047' ;


SELECT D.DEPARTMENT_NAME AS 학과이름,
       S.STUDENT_NAME AS 학생이름,
       P.PROFESSOR_NAME AS 지도교수이름
FROM   TB_STUDENT S   
JOIN   TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN   TB_DEPARTMENT D ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE  STUDENT_NO = 'A313047' ;


--12. 2007년도에 인간관계론 과목을 수강한 학생을 찾아 학생이름과 수강학기를 표시하는 SQL문장을 작성하시오
SELECT *
FROM   TB_STUDENT ;
SELECT *
FROM   TB_CLASS ;
SELECT *
FROM   TB_GRADE ;

SELECT STUDENT_NAME,
       TERM_NO
FROM   TB_STUDENT
JOIN   TB_GRADE USING(STUDENT_NO)
JOIN   TB_CLASS USING(CLASS_NO)
WHERE  CLASS_NAME = '인간관계론' 
AND    SUBSTR(TERM_NO,1,4) = '2007' ;

--13. 예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목을 찾아 그 과목이름과 학과이름을 출력하는 문장을 작성하시오
SELECT *
FROM   TB_DEPARTMENT ;

SELECT *
FROM   TB_CLASS ;

SELECT *
FROM   TB_STUDENT ;

SELECT *
FROM   TB_CLASS_PROFESSOR ;

SELECT *
FROM   TB_PROFESSOR ;

SELECT C.CLASS_NAME,
       D.DEPARTMENT_NAME
FROM   TB_DEPARTMENT D
LEFT JOIN   TB_CLASS C USING(DEPARTMENT_NO)
LEFT JOIN   TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
WHERE  CATEGORY = '예체능' AND PROFESSOR_NO IS NULL ;
----LEFT하면 나오고 LEFT 안쓰면 안나오는데..?

--14. 춘기술대 서반어어과 학생들의 지도교수를 게시하고자 한다.학생이름과 지도교수 이름을 찾고 만약 지도 교수가 없는 학생인 경우 지도교수 미지정으로
--표시하도록 하는 SQL을 작성하시오(단 헤더는 학생이름,지도교수로 표시하며 고학번학생이 먼저 표시되도록한다)
SELECT *
FROM   TB_STUDENT ;

SELECT STUDENT_NAME 학생이름,
       DECODE(PROFESSOR_NAME,NULL,'지도교수미지정',PROFESSOR_NAME) 지도교수 
FROM   TB_DEPARTMENT 
LEFT JOIN   TB_STUDENT  USING(DEPARTMENT_NO)
LEFT JOIN   TB_PROFESSOR  ON(COACH_PROFESSOR_NO = PROFESSOR_NO) 
WHERE  DEPARTMENT_NAME = '서반아어학과' 
ORDER BY STUDENT_NO DESC ;
---  LEFT조인하니까 나오네..
    
--15. 휴학생이 아닌 학생 중 평점이 4.0이상인 학생을 찾아 그 학생의 학번,이름,학과이름,평점을 출력하는 SQL문을 작성하시오
SELECT *
FROM   TB_STUDENT ;

SELECT *
FROM   TB_GRADE ;

SELECT *
FROM   TB_DEPARTMENT ;

SELECT STUDENT_NO,
       STUDENT_NAME,
       DEPARTMENT_NAME,
       AVG(POINT)
FROM   TB_DEPARTMENT
JOIN   TB_STUDENT USING(DEPARTMENT_NO)
JOIN   TB_GRADE USING(STUDENT_NO)
WHERE  ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING AVG(POINT) >= 4.0 ;


--16. 환경조경학과 전공과목들의 과목별 평점을 파악할 수 있는 SQL문을 작성하시오
SELECT CLASS_NO,
       CLASS_NAME,
       AVG(POINT)
FROM   TB_DEPARTMENT
JOIN   TB_CLASS USING(DEPARTMENT_NO)
JOIN   TB_GRADE USING(CLASS_NO)
WHERE  DEPARTMENT_NAME = '환경조경학과'
AND    CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME ;

--17. 춘 기술대학교에 다니고 있는 최경희 학생과 같은 과 학생들의 이름과 주소를 출력하는 SQL문을 작성하시오
SELECT *
FROM   TB_STUDENT ;

SELECT *
FROM   TB_DEPARTMENT ;

SELECT STUDENT_NAME,
       STUDENT_ADDRESS
FROM   TB_STUDENT
WHERE  DEPARTMENT_NO = (SELECT STUDENT_NAME
                        FROM   TB_STUDENT
                        WHERE  STUDENT_NAME = '최경희') ;
                        
SELECT STUDENT_NAME,
       STUDENT_ADDRESS
FROM   TB_STUDENT
WHERE  DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                         FROM   TB_STUDENT
                         WHERE  STUDENT_NAME = '최경희') ; 




--18.국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하는 SQL문을 작성 (인라인뷰로 최상위 결과 하나만 가져올 수도 있음)
SELECT STUDENT_NAME,
       STUDENT_NO
FROM  TB_DEPARTMENT
JOIN  TB_STUDENT USING(DEPARTMENT_NO)
JOIN  TB_GRADE   USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NAME, STUDENT_NO 
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                     FROM TB_GRADE
                     GROUP BY STUDENT_NAME, STUDENT_NO);
---왜 틀렸을까??

SELECT ROWNUM,
       STUDENT_NAME,
       STUDENT_NO
FROM  (SELECT STUDENT_NAME, STUDENT_NO
        FROM(SELECT STUDENT_NO,
                    AVG(POINT)
              FROM TB_GRADE
              GROUP BY STUDENT_NO
              ORDER BY 2 DESC)
        JOIN TB_STUDENT USING(STUDENT_NO)
        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
        WHERE DEPARTMENT_NAME = '국어국문학과'
        AND  ROWNUM = 1
        GROUP BY STUDENT_NAME, STUDENT_NO
        ) ;

--19. 춘기술대학교의 "환경조경학과"가 속한 같은 계열 학과들의 학과별 전공과목 평점을 파악하기 위한 SQL문을 찾으시오(헤더는 "계열 학과명", "전공평점"으로 표시되고 평점은 소수점 한자리까지 반올림)
SELECT *
FROM   TB_DEPARTMENT ;
SELECT *
FROM   TB_CLASS ;
SELECT *
FROM   TB_GRADE ;

SELECT DEPARTMENT_NAME AS "계열 학과명", 
       ROUND(AVG(POINT),1) AS 전공평점
FROM   TB_DEPARTMENT
JOIN   TB_CLASS USING(DEPARTMENT_NO)
JOIN   TB_GRADE USING(CLASS_NO)
WHERE  CATEGORY = (SELECT CATEGORY
                   FROM   TB_DEPARTMENT
                   WHERE  DEPARTMENT_NAME = '환경조경학과')
AND    CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME ;