-- basic select
-- 1.춘 기술대학교의 학과이름과 계열 표시(출력 헤더 "학과 명", "계열")
SELECT *
FROM   TB_DEPARTMENT ;

SELECT DEPARTMENT_NAME AS "학과 명", 
       CATEGORY AS "계열"
FROM   TB_DEPARTMENT ;

-- 2. 학과의 학과정원

SELECT DEPARTMENT_NAME||'의 정원은'||CAPACITY||'명 입니다'
FROM   TB_DEPARTMENT ;

-- 3. 국어국문학과 다니는 여학생 중 현재 휴학중인 여학생을 찾아라

SELECT DEPARTMENT_NO
FROM   TB_DEPARTMENT
WHERE  DEPARTMENT_NAME = '국어국문학과' ; 

SELECT STUDENT_NAME, ABSENCE_YN
FROM   TB_STUDENT
WHERE  DEPARTMENT_NO = '001' 
AND    ABSENCE_YN = 'Y'
AND    STUDENT_SSN LIKE '_______2%' ;

SELECT STUDENT_SSN
FROM   TB_STUDENT ; 

-- 4. 도서관에서 대출도서 장기연체자들을 찾아 이름을 게시한다
SELECT *
FROM   TB_STUDENT ;

SELECT STUDENT_NO, STUDENT_NAME
FROM   TB_STUDENT
WHERE  STUDENT_NO = 'A513079'
OR STUDENT_NO = 'A513090'
OR STUDENT_NO = 'A513091'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513119' ;

--5. 입학정원이 20명이상 30명 이하인 학과들의 학과 이름과 계열
SELECT DISTINCT DEPARTMENT_NAME, CATEGORY
FROM   TB_DEPARTMENT
WHERE  CAPACITY >= '20'
AND    CAPACITY <= '30' ;


--6. 총장을 제외하고는 모든 교수들이 소속 학과를 가지고 있다.이때 춘 기술대학교 총장의 이름을 알아내라
SELECT DEPARTMENT_NO, PROFESSOR_NAME
FROM   TB_PROFESSOR ;

SELECT PROFESSOR_NAME
FROM   TB_PROFESSOR
WHERE  DEPARTMENT_NO IS NULL ;

--7. 전산상 착오로 학과가 지정되어 있지 않은 학생확인
SELECT STUDENT_NAME
FROM   TB_STUDENT
WHERE  DEPARTMENT_NO IS NULL ;

--8. 선수과목이 존재하는 과목들은 어떤과목인지 과목번호 조회
SELECT CLASS_NO
FROM   TB_CLASS
WHERE  PREATTENDING_CLASS_NO IS NOT NULL ;

--9. 춘 대학교 계열 조회
SELECT DISTINCT CATEGORY
FROM   TB_DEPARTMENT ;

--10. 02학번 전주거주자모임을 만들려고하는데 휴학생은 제외하고 재학중인 학생들의 학번 이름 주민번호를 출력하라
SELECT *
FROM   TB_STUDENT ;

SELECT STUDENT_NO, 
       STUDENT_NAME,
       STUDENT_SSN
FROM   TB_STUDENT
WHERE  ABSENCE_YN = 'N'
AND    ENTRANCE_DATE LIKE '02%'
AND    STUDENT_ADDRESS LIKE '전주시%' ;