--1.
CREATE TABLE TB_CATEGORY
(NAME  VARCHAR(10),
 USE_YN CHAR(1) DEFAULT 'Y');
 
--2.
CREATE TABLE TB_CLASS_TYPE
 (NO   VARCHAR2(5) PRIMARY KEY,
  NAME  VARCHAR2(10));
  
--3.
ALTER TABLE TB_CATEGORY
MODIFY NAME PRIMARY KEY ;

--4.
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL ;

--5.
ALTER TABLE TB_CLASS_TYPE
MODIFY(CLASS_TYPE_NO  VARCHAR(10));

ALTER TABLE TB_CATEGORY
MODIFY(CATEGORY_NAME  VARCHAR(20));

SELECT *
FROM  TB_CATEGORY;

SELECT *
FROM  TB_CLASS_TYPE;

--6.
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO ;


--7.
ALTER TABLE TB_CATEGORY
RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;

--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

--9.
ALTER TABLE TB_DEPARTMENT MODIFY CATEGORY REFERENCES TB_CATEGORY(PK_CATEGORY_NAME); 
ALTER TABLE TB_DEPARTMENT RENAME COLUMN CATEGORY TO FK_DEPARTMENT_CATEGORY ;

--10.
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO AS 학번,
          STUDENT_NAME AS 학생이름,
          STUDENT_ADDRESS AS 주소
   FROM  TB_STUDENT ;
SELECT*
FROM  VW_학생일반정보;
--11.
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME AS 학생이름,
          DEPARTMENT_NAME AS 학과이름,
          PROFESSOR_NAME AS 지도교수이름
   FROM   TB_DEPARTMENT
   JOIN   TB_PROFESSOR USING(DEPARTMENT_NO)
   RIGHT JOIN   TB_STUDENT ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
   ORDER BY 2;
SELECT *
FROM VW_지도면담;

--12.
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME,
          COUNT(*) AS STUDENT_COUNT
   FROM   TB_DEPARTMENT
   JOIN   TB_STUDENT USING(DEPARTMENT_NO)
   GROUP BY DEPARTMENT_NAME ;
SELECT *
FROM  VW_학과별학생수;

--13.
UPDATE VW_학생일반정보
SET    학생이름 = '김한준'
WHERE  학번 = 'A213046';

--14.
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO AS 학번,
          STUDENT_NAME AS 학생이름,
          STUDENT_ADDRESS AS 주소
   FROM  TB_STUDENT 
WITH READ ONLY;

--15.
SELECT *
FROM   TB_GRADE;

SELECT CLASS_NO, CLASS_NAME,COUNT(*)
FROM (SELECT SUBSTR(TERM_NO,1,4),CLASS_NO,CLASS_NAME,COUNT(*)
      FROM  TB_CLASS
      JOIN  TB_GRADE USING(CLASS_NO)
      GROUP BY TERM_NO,CLASS_NO, CLASS_NAME)
WHERE ROWNUM <= 3
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY COUNT(*) DESC ;


SELECT CLASS_NO, CLASS_NAME,COUNT(*)
FROM (SELECT SUBSTR(TERM_NO,1,4),CLASS_NO,CLASS_NAME,COUNT(*)
      FROM  TB_CLASS
      JOIN  TB_GRADE USING(CLASS_NO)
      GROUP BY SUBSTR(TERM_NO,1,4),CLASS_NO, CLASS_NAME
      ORDER BY 4)
WHERE ROWNUM <= 3
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY COUNT(*) DESC ;


--------------------

SELECT *
FROM TB_GRADE 
ORDER BY TERM_NO DESC;

SELECT CLASS_NO,
       DEPARTMENT_NAME,
       CNT
FROM   (SELECT CLASS_NO,
               COUNT(*) AS CNT
        FROM   TB_GRADE
        WHERE  SUBSTR(TERM_NO,1,4) BETWEEN '2007' AND '2009'
        GROUP BY CLASS_NO
        ORDER BY 2 DESC)
JOIN   TB_CLASS USING (CLASS_NO)
JOIN   TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE  ROWNUM <= 3
ORDER BY 3 DESC ;

