SELECT *
FROM   COLUMN_LENGTH ;

SELECT LENGTH(CHARTYPE),
       LENGTH(VARCHARTYPE)
FROM   COLUMN_LENGTH ;      

SELECT *
FROM   EMPLOYEE ;

SELECT EMAIL,
       INSTR(EMAIL,'c',-1,2) 위치
FROM   EMPLOYEE ;

SELECT EMAIL,
       INSTR(EMAIL,'c',INSTR(EMAIL, '.')-1 ) 위치
FROM   EMPLOYEE ;

SELECT EMAIL AS 원본데이터,
       LENGTH(EMAIL) AS 원본길이,
       LPAD(EMAIL, 20,'.') AS 적용결과,
       LENGTH(LPAD(EMAIL, 20, '.')) AS 결과길이
FROM   EMPLOYEE ;

SELECT EMAIL 원본데이터,
       LENGTH(EMAIL) 원본길이,
       RPAD(EMAIL, 20, '.') 적용결과,
       LENGTH(LPAD(EMAIL, 20, '.')) 결과길이
FROM   EMPLOYEE ;

--TRIM에서 '123'은 123이 아니라 1또는 2또는 3을 만났을때 제거, 데이터 대소문자 구분
SELECT LTRIM('   tech')
FROM   DUAL ;

SELECT LTRIM('   tech', '.')
FROM   DUAL ;

SELECT LTRIM('000123', '0')
FROM   DUAL ;

SELECT LTRIM('123123tech', '123')
FROM  DUAL ;

SELECT LTRIM('123123tech123', '123')
FROM DUAL ;

SELECT LTRIM('xyxzyytech', 'xyz') 
FROm DUAL ;

SELECT LTRIM('6372tech', '01234567889')
FROM DUAL ;

SELECT RTRIM('tech   ')
FROM   DUAL ;

SELECT RTRIM('tech...', '.')
FROM   DUAL ;

SELECT RTRIM('tech11123', '123')
FROM   DUAL ;

SELECT RTRIM('123tech123', '123')
FROM   DUAL ;

SELECT RTRIM('XYZtechXYZ', 'XYZ')
FROm   DUAL ;

SELECT RTRIM('xyztechXyz', 'Xyz')
FROm   DUAL ;

SELECT TRIM('  tech  ')
FROM   DUAL ;

SELECT TRIM('a' FROM 'aatechaaa')
FROM   DUAL ;

SELECT TRIM(LEADING '0' FROM '000123')
FROM   DUAL ;

SELECT TRIM(TRAILING '1' FROM 'TECH1') 
FROM   DUAL ;

SELECT TRIM(BOTH '1' FROM '123tech111')
FROM   DUAL ;

SELECT TRIM(LEADING '.' FROM '..tech..')
FROM   DUAL ;
--------------TRIM에서 '123'은 123이 아니라 1또는 2또는 3을 만났을때 제거, 데이터 대소문자 구분

SELECT SUBSTR('This is a test', 6, 2) 
FROM   DUAL ;

SELECT SUBSTR('This is a test', 6)
FROM   DUAL ;

SELECT SUBSTR('이것은 연습입니다', 3, 4)
FROm   DUAL ;

SELECT SUBSTR('TechOnTheNet', 1, 4)
FROM   DUAL ;

SELECT SUBSTR('TechOnTheNet', -3,3)
FROm   DUAL ;

SELECT SUBSTR('TechOnTheNet', -6,3)
FROM   DUAL ;

SELECT SUBSTR('TechOnTheNet', -8,2)
FROM   DUAL ;

SELECT *
FROM   EMPLOYEE ;

-- 사원테이블에서 입사년월일에서 입사년도만 출력하세요!!
-- "            사원의 이메일에서 메일아이디만 출력하세요!!
SELECT SUBSTR(HIRE_DATE, 1, 2)
FROM   EMPLOYEE ;

SELECT EMAIL,
       SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)
FROM   EMPLOYEE ;

SELECT EMAIL,
       SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)
FROM   EMPLOYEE
WHERE  LENGTH(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)) >= 6 ;

SELECT ROUND(125.315)
FROM   DUAL ;

SELECT ROUND(125.315, 0)
FROM   DUAL ; 

SELECT ROUND(125.315, -1)
FROM   DUAL ; 

SELECT ROUND(125.315, 3)
FROM  DUAL ;

SELECT ROUND(-125.315, -1)
FROM  DUAL ;

SELECT TRUNC(125.315, -1)
FROM   DUAL ;

SELECT TRUNC(-125.315, -3)
FROM   DUAL ;

SELECT SYSDATE
FROM   DUAL ;

---사원테이블에서 입사일을 기준으로 근무연수가 20년이 되는 일자를 조회하라
SELECT *
FROM   EMPLOYEE ;

SELECT HIRE_DATE,
       ADD_MONTHS(HIRE_DATE, 240)
FROM   EMPLOYEE ;

---현재 날짜를 기준으로 근속년수가 20년 이상인 사원의 이름, 입사일, 근속년수를 조회하세요
SELECT SYSDATE
FROM   DUAL ;

SELECT *
FROM   EMPLOYEE ;

SELECT EMP_NAME AS 이름,
       HIRE_DATE AS 입사일,
       TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12) AS 근속년수
FROM   EMPLOYEE 
WHERE  MONTHS_BETWEEN(SYSDATE, HIRE_DATE) >= 240 ;

SELECT *
FROM   EMPLOYEE ;

SELECT SUBSTR(EMP_NO, 1, 6) AS "앞자리",
       SUBSTR(EMP_NO, 8) AS "뒷자리",
       SUBSTR(EMP_NO, 1, 6) + SUBSTR(EMP_NO, 8),
       TO_NUMBER(SUBSTR(EMP_NO , 1, 6) ) + TO_NUMBER(SUBSTR(EMP_NO , 8) )
FROM   EMPLOYEE ;

--사원테이블에서 여자 사원의 이름, 주민번호를 조회하세요!
SELECT *
FROM   EMPLOYEE ;

SELECT EMP_NO,
       EMP_NAME
FROM   EMPLOYEE 
WHERE  SUBSTR(EMP_NO, 8, 1) = 2 ;

SELECT EMP_NO,
       EMP_NAME
FROM   EMPLOYEE 
WHERE  TO_NUMBER(SUBSTR(EMP_NO, 8, 1) ) = 2 ;

--숫자라고 해서 다 그냥 쓸수는 없고 숫자여도 문자나 날짜로 쓰인건 ''표시
--오라클에는 DUAL이라는 더미테이블 존재
--CHAR(20)이면 영문일때는 그대로 20 호출하고 CHAR(20)이면 한글일때는 컬럼길이(20바이트)-데이터길이(한글 1글자=3바이트일때 엘지씨엔에스이면 x6글자면 18바이트)=2바이트, 엘지씨엔에스 + (컬럼길이에서 데이터길이 뺀 공백 2바이트) = 8

SELECT TO_CHAR(1234, '99999') 
FROM   DUAL ;

SELECT TO_CHAR(1234, '09999')
FROM   DUAL ;

SELECT TO_CHAR(1234, 'L99999')
FROM   DUAL ;

SELECT TO_CHAR(1234, '99,999')
FROM   DUAL ;

SELECT TO_CHAR(1234, '09,999')
FROM   DUAL ;

SELECT TO_CHAR(1234, '999')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'PM HH24:MI:SS')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'AM HH:MI:SS')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'MON DY, YYYY')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'YYYY-fmMM-DD DAY')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-fmDD DAY')
FROM   DUAL ;

SELECT TO_CHAR(SYSDATE, 'Year, Q')
FROM   DUAL ;

SELECT EMP_NAME AS 이름,
       TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') AS 입사일
FROM   EMPLOYEE
WHERE  JOB_ID = 'J7' ;

SELECT EMP_NAME AS 이름,
       TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') AS 입사일
FROM   EMPLOYEE
WHERE  JOB_ID = 'J7' ;

SELECT EMP_NAME AS 이름,
       SUBSTR(HIRE_DATE,1,2) ||'년'|| SUBSTR(HIRE_DATE,4,2) ||'월'|| SUBSTR(HIRE_DATE,7,2) ||'일' AS 입사일
FROM   EMPLOYEE
WHERE  JOB_ID = 'J7' ;

SELECT EMP_NAME AS 이름,
       HIRE_DATE AS 기본입사일,
       TO_CHAR(HIRE_DATE, 'YYYY/MM/DD HH24:MI:SS') AS 상세입사일
FROM   EMPLOYEE
WHERE  JOB_ID IN('J1', 'J2') ;

SELECT EMP_NAME
FROM   EMPLOYEE
WHERE  HIRE_DATE = '04/04/30' ;

SELECT EMP_NAME
FROM   EMPLOYEE
WHERE  HIRE_DATE = '90/04/01' ;
--날짜정보가 없을때는 월/일만가지고도 비교가능하지만 날짜정보가 있을때는 비교불가함(이럴때는 다른 접근이 필요)
SELECT EMP_NAME,
       HIRE_DATE
FROM   EMPLOYEE
WHERE  HIRE_DATE = TO_DATE('900401 133030', 'YYMMDD HH24MISS') ;

SELECT EMP_NAME,
       HIRE_DATE
FROM   EMPLOYEE
WHERE  TO_CHAR(HIRE_DATE, 'YYMMDD') = '900401' ;

-------

SELECT TO_DATE('20100101', 'YYYYMMDD')
FROM   DUAL ;

SELECT TO_CHAR('20100101', 'YYYY, MON')
FROM   DUAL ;

SELECT TO_CHAR( TO_DATE('20100101', 'YYYYMMDD'), 'YYYY, MON')
FROM   DUAL ;

SELECT TO_DATE( '041030 143000', 'YYMMDD HH24MISS')
FROM   DUAL ;

SELECT TO_CHAR( TO_DATE('041030 143000', 'YYMMDD HH24MISS'), 'DD-MON-YY HH:MI:SS PM')
FROM   DUAL ;

SELECT TO_DATE( '980630', 'YYMMDD')
FROM   DUAL ;

SELECT TO_CHAR( TO_DATE('980630', 'YYMMDD'), 'YYYY.MM.DD')
FROM   DUAL ;

SELECT EMP_NAME,
       HIRE_DATE,
       TO_CHAR(HIRE_DATE, 'YYYY/MM/DD')
FROM   EMPLOYEE
WHERE  EMP_NAME = '한선기' ;

SELECT '2009/10/14' AS 현재,
       '95/10/27' AS 입력,
       TO_CHAR(TO_DATE('95/10/27', 'YY/MM/DD'), 'YYYY/MM/DD') AS YY형식1,
       TO_CHAR(TO_DATE('95/10/27', 'YY/MM/DD'), 'RRRR/MM/DD') AS YY형식2,
       TO_CHAR(TO_DATE('95/10/27', 'RR/MM/DD'), 'YYYY/MM/DD') AS RR형식1,
       TO_CHAR(TO_DATE('95/10/27', 'RR/MM/DD'), 'RRRR/MM/DD') AS RR형식2
FROM   DUAL ;
